version: '2'
services:
  tfgmirko-app:
    image: tfgmirko
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tfgmirko-postgresql:5432/tfgmirko
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 6000:6000
  tfgmirko-postgresql:
    extends:
      file: postgresql.yml
      service: tfgmirko-postgresql
